
FROM rust:1.87.0

RUN rustup target add wasm32-unknown-unknown

COPY my-canister-dashboard-rs /app/my-canister-dashboard-rs
WORKDIR /app/my-canister-dashboard-rs

RUN mkdir -p wasm && \
    cargo build --target wasm32-unknown-unknown --release --package my-canister-installer --locked && \
    cp target/wasm32-unknown-unknown/release/my_canister_installer.wasm wasm/my-canister-installer.wasm
