name: CI

on:
  push:
    tags:
      - '*'

jobs:
  deterministic-build:
    name: Deterministic Build Verification
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Run deterministic build and hash verification
        run: ./scripts/github-deterministic-build.sh