name: PR Validation

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    name: PR Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Run prerelease checks
        run: ./scripts/prerelease.sh
        
      - name: Run deterministic build verification
        run: ./scripts/github-deterministic-build.sh